[
  {
    "id" : "a21f9545-d846-4653-8fc6-ec39e504d361",
    "prId" : 9864,
    "prUrl" : "https://github.com/tensorflow/tensorflow/pull/9864#pullrequestreview-38726834",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "cb27d8b3-b294-4382-902f-cf6de2cfbb63",
        "parentId" : null,
        "authorId" : "c58d0887-9ab4-4777-b96b-33561a3bb573",
        "body" : "Someday you may want to propagate the bad status further along, rather than CHECK failing.  Ok for now, though.",
        "createdAt" : "2017-05-17T17:45:48Z",
        "updatedAt" : "2017-05-24T08:41:03Z",
        "lastEditedBy" : "c58d0887-9ab4-4777-b96b-33561a3bb573",
        "tags" : [
        ]
      }
    ],
    "commit" : "047546d6fee2549c5963a338cdcc2ac801097d76",
    "line" : 200,
    "diffHunk" : "@@ -1,1 +198,202 @@      const Rendezvous::Args& recv_args, const Tensor& val, bool is_dead) {\n    if (!status.ok()) {\n      CHECK(status.ok()) << \"RecvLocalAsync was not ok, key: \"\n                         << parsed.FullKey() << \" step: \" << step_id\n                         << \" error message: \" << status.error_message();"
  }
]