[
  {
    "id" : "bde96650-c4c0-4544-bda4-e24706cc19ff",
    "prId" : 15714,
    "prUrl" : "https://github.com/numpy/numpy/pull/15714#pullrequestreview-370781067",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "parentId" : null,
        "authorId" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "body" : "These four lines should probably become `check_output`, so we don't ignore failures.",
        "createdAt" : "2020-03-06T07:53:39Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "tags" : [
        ]
      },
      {
        "id" : "6c3f25b1-48fb-46c4-a886-c1cf3156481a",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "body" : "Changed the default nm, could just remove the shell argument completely if we consider this private API though.",
        "createdAt" : "2020-03-06T18:25:43Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "tags" : [
        ]
      },
      {
        "id" : "0533463b-a00d-4a65-9184-4d5491e18831",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "body" : "I suppose `check_output` would result in different handling of `nm_err`.",
        "createdAt" : "2020-03-06T18:52:26Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "tags" : [
        ]
      },
      {
        "id" : "52aecba4-8419-4f39-90ad-55eafeb87f8e",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "body" : "True, I suppose it could mean that someone has to use a try/except clause in theory. But it may also catch issues in practice? If we want to backport this, could be better to just leave it in place though?",
        "createdAt" : "2020-03-06T19:29:42Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "tags" : [
        ]
      },
      {
        "id" : "c95a9ad6-ebe5-424e-a194-51197ac66c5b",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "body" : "I do not know distutils well enough to make a judgement call about whether or not such a change is fine. It seems fine to me in the regard that it should be fairly straight forward to track down by someone skilled in basic python debugging... @rgommers thoughts?",
        "createdAt" : "2020-03-06T20:03:43Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "b0342685-bd89-441f-a04f-0e75db24c07f",
        "tags" : [
        ]
      },
      {
        "id" : "f8e971c2-d781-4e6d-8ecb-ffd4b6a13451",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "body" : "I don't think it matters. `check_output` would put it on stdout, this puts it in the exception message, which is perhaps nicer.\r\n\r\nUsing `subprocess.run` might be a little tidier while keeping the behavior, but it doesn't really matter.",
        "createdAt" : "2020-03-07T12:38:43Z",
        "updatedAt" : "2020-03-07T16:27:12Z",
        "lastEditedBy" : "ab55dc5f-f626-43b1-ba83-3d8843d79a45",
        "tags" : [
        ]
      },
      {
        "id" : "6df4e131-e9a3-4f74-b45e-a7c88fbf4beb",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "919d650d-5f9e-4069-90f7-968e2cf7bb16",
        "body" : "I changed this to capture and discard stderr (if returncode is OK) since running nm on the 32-bit `*lib` generates lots of warnings on stderr. In fact, the `nm_output` returned by this is not correctly parsed by the regex, so at least on my machine the `*.DEF` file and the subsequent `*.a` generated is not at all useful. But fixing that should be a seperate PR.",
        "createdAt" : "2020-03-07T18:19:46Z",
        "updatedAt" : "2020-03-07T18:19:46Z",
        "lastEditedBy" : "919d650d-5f9e-4069-90f7-968e2cf7bb16",
        "tags" : [
        ]
      },
      {
        "id" : "be5a5545-6808-48ed-924f-63837fa82424",
        "parentId" : "a567ba05-2bc5-4f48-8401-29f7604b0238",
        "authorId" : "919d650d-5f9e-4069-90f7-968e2cf7bb16",
        "body" : "Edit \"running the 64-bit nm on the 32-bit `*.lib`\"",
        "createdAt" : "2020-03-07T18:20:27Z",
        "updatedAt" : "2020-03-07T18:20:28Z",
        "lastEditedBy" : "919d650d-5f9e-4069-90f7-968e2cf7bb16",
        "tags" : [
        ]
      }
    ],
    "commit" : "f984e3ae3d2dc5bdfc2fa9d8b44ccb727e319575",
    "line" : 28,
    "diffHunk" : "@@ -1,1 +70,74 @@        raise RuntimeError('failed to run \"%s\": \"%s\"' % (\n                                     ' '.join(nm_cmd), nm_err))\n    return nm_output\n\ndef parse_nm(nm_output):"
  }
]