[
  {
    "id" : "80712bde-42de-41e9-b42b-2045c9f003ca",
    "prId" : 21070,
    "prUrl" : "https://github.com/ansible/ansible/pull/21070#pullrequestreview-68242575",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "a09d9ddd-918f-4712-b599-6fcaf6140285",
        "parentId" : null,
        "authorId" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "body" : "Also, add ```vmodl.fault.SystemError``` here,",
        "createdAt" : "2017-10-09T06:14:03Z",
        "updatedAt" : "2017-10-17T11:45:19Z",
        "lastEditedBy" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "tags" : [
        ]
      },
      {
        "id" : "17eb50c2-aa30-4b5a-931c-d203b487be31",
        "parentId" : "a09d9ddd-918f-4712-b599-6fcaf6140285",
        "authorId" : "a27763b1-e4bf-48d7-8230-f5d371298f7b",
        "body" : "Hi @Akasurde . Do you mean than only the vmodl.fault.SystemError needs to exit maintenance?",
        "createdAt" : "2017-10-09T11:51:24Z",
        "updatedAt" : "2017-10-17T11:45:19Z",
        "lastEditedBy" : "a27763b1-e4bf-48d7-8230-f5d371298f7b",
        "tags" : [
        ]
      },
      {
        "id" : "f739eeb6-23ea-4016-a6f7-ae8a18556b34",
        "parentId" : "a09d9ddd-918f-4712-b599-6fcaf6140285",
        "authorId" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "body" : "No, I mean\r\n\r\n```\r\nexcept (vmodl.fault.SystemError, Exception) as e:\r\n```",
        "createdAt" : "2017-10-09T12:11:05Z",
        "updatedAt" : "2017-10-17T11:45:19Z",
        "lastEditedBy" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "tags" : [
        ]
      },
      {
        "id" : "42faf602-ec68-408d-a150-c1278ba50d38",
        "parentId" : "a09d9ddd-918f-4712-b599-6fcaf6140285",
        "authorId" : "a27763b1-e4bf-48d7-8230-f5d371298f7b",
        "body" : "Thanks for the clarification Akasurde. However, I am pretty sure that \"Exception\" catches the \"vmodl.fault.SystemError\" too.",
        "createdAt" : "2017-10-10T09:02:54Z",
        "updatedAt" : "2017-10-17T11:45:19Z",
        "lastEditedBy" : "a27763b1-e4bf-48d7-8230-f5d371298f7b",
        "tags" : [
        ]
      },
      {
        "id" : "1eb26c79-6611-444d-99d5-ad605228c498",
        "parentId" : "a09d9ddd-918f-4712-b599-6fcaf6140285",
        "authorId" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "body" : "ok.",
        "createdAt" : "2017-10-10T11:08:23Z",
        "updatedAt" : "2017-10-17T11:45:19Z",
        "lastEditedBy" : "96aeecbb-c275-402c-b904-a795c82efb48",
        "tags" : [
        ]
      }
    ],
    "commit" : "cde41007081da67b4206191484d40e081ccf01ae",
    "line" : 143,
    "diffHunk" : "@@ -1,1 +141,145 @@            self.host.configManager.firmwareSystem.RestoreFirmwareConfiguration(force=True)\n            self.module.exit_json(changed=True)\n        except Exception as e:\n            self.exit_maintenance()\n            self.module.fail_json(msg=str(e))"
  }
]