[
  {
    "id" : "2cefd32d-c2be-4f4b-913f-d193a4fb1484",
    "prId" : 27488,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/27488#pullrequestreview-266862976",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "30e351ff-6a95-4542-8260-101138a94331",
        "parentId" : null,
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "this is failing for me locally",
        "createdAt" : "2019-07-25T19:41:33Z",
        "updatedAt" : "2019-07-25T19:41:33Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      },
      {
        "id" : "94284148-1acf-4cc1-8156-d097ecede1df",
        "parentId" : "30e351ff-6a95-4542-8260-101138a94331",
        "authorId" : "21b82015-4bfc-4f74-bfca-586973dad2cd",
        "body" : "What are you seeing?",
        "createdAt" : "2019-07-25T20:01:41Z",
        "updatedAt" : "2019-07-25T20:01:41Z",
        "lastEditedBy" : "21b82015-4bfc-4f74-bfca-586973dad2cd",
        "tags" : [
        ]
      },
      {
        "id" : "0b7aa889-0604-4fa2-b179-883d3b983d03",
        "parentId" : "30e351ff-6a95-4542-8260-101138a94331",
        "authorId" : "21b82015-4bfc-4f74-bfca-586973dad2cd",
        "body" : "Oh, I'm guessing it's a `KeyError: 'pandas_plotting_backends'`?\r\n\r\nYou'll need to re-run `python -m pip install -e .` in your pandas directory. This adds the entrypoint.",
        "createdAt" : "2019-07-25T20:03:00Z",
        "updatedAt" : "2019-07-25T20:03:00Z",
        "lastEditedBy" : "21b82015-4bfc-4f74-bfca-586973dad2cd",
        "tags" : [
        ]
      },
      {
        "id" : "ea2f3f44-e624-4447-b601-349714bcfb00",
        "parentId" : "30e351ff-6a95-4542-8260-101138a94331",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "Yep that does fix it, thanks",
        "createdAt" : "2019-07-25T20:21:49Z",
        "updatedAt" : "2019-07-25T20:21:50Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      }
    ],
    "commit" : "69c306948080ba851eb5e43bdd9b985e422e73af",
    "line" : 19,
    "diffHunk" : "@@ -1,1 +46,50 @@\n@td.skip_if_no_mpl\ndef test_register_entrypoint():\n    mod = types.ModuleType(\"my_backend\")\n    mod.plot = lambda *args, **kwargs: 1"
  },
  {
    "id" : "65eba705-9168-48aa-a236-63677666cd3c",
    "prId" : 27810,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/27810#pullrequestreview-272575054",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "96617373-2054-442a-861e-9037dfe5dabe",
        "parentId" : null,
        "authorId" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "body" : "why doesn't this work in this case?",
        "createdAt" : "2019-08-08T11:59:32Z",
        "updatedAt" : "2019-08-08T11:59:35Z",
        "lastEditedBy" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "tags" : [
        ]
      },
      {
        "id" : "e1596e9b-52a2-4092-8593-d407a1251f8e",
        "parentId" : "96617373-2054-442a-861e-9037dfe5dabe",
        "authorId" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "body" : "The issue is running the tests from a non-virtualenv-like setup.  So matplotlib _is_ installed, but the pandas being tested is not in site-packages",
        "createdAt" : "2019-08-08T13:36:23Z",
        "updatedAt" : "2019-08-08T13:36:23Z",
        "lastEditedBy" : "adf621f1-4745-479a-a1fc-dc14046a3f4b",
        "tags" : [
        ]
      }
    ],
    "commit" : "5efacb89d3093ad44335824c4485e1b114ce5f72",
    "line" : 2,
    "diffHunk" : "@@ -1,1 +45,49 @@\n\n@td.skip_if_no_mpl\ndef test_register_entrypoint():\n"
  }
]