[
  {
    "id" : "f057768b-90e5-4be4-982c-d69bda04968f",
    "prId" : 36299,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/36299#pullrequestreview-564815711",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "8e1f4de3-0490-47bb-925e-d1830980db64",
        "parentId" : null,
        "authorId" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "body" : "can use double backticks fro Index",
        "createdAt" : "2021-01-09T22:31:32Z",
        "updatedAt" : "2021-03-02T20:43:24Z",
        "lastEditedBy" : "7086d5c0-382b-4c41-b70d-144a07643f71",
        "tags" : [
        ]
      },
      {
        "id" : "33b87ad7-954b-4833-8375-8e48527c382c",
        "parentId" : "8e1f4de3-0490-47bb-925e-d1830980db64",
        "authorId" : "f3e7d5fe-a112-47db-9178-8be42b4a8eab",
        "body" : "Done",
        "createdAt" : "2021-01-09T22:45:13Z",
        "updatedAt" : "2021-03-02T20:43:24Z",
        "lastEditedBy" : "f3e7d5fe-a112-47db-9178-8be42b4a8eab",
        "tags" : [
        ]
      }
    ],
    "commit" : "0af939d8a964a8039fc9f94444be14c18fbed1e4",
    "line" : 4,
    "diffHunk" : "@@ -1,1 +420,424 @@Indexing\n^^^^^^^^\n\n- Bug in :meth:`Index.union` dropping duplicate ``Index`` values when ``Index`` was not monotonic or ``sort`` was set to ``False`` (:issue:`36289`, :issue:`31326`)\n- Bug in :meth:`CategoricalIndex.get_indexer` failing to raise ``InvalidIndexError`` when non-unique (:issue:`38372`)"
  },
  {
    "id" : "5548d4ff-0b62-40b1-be90-938f350cb512",
    "prId" : 37367,
    "prUrl" : "https://github.com/pandas-dev/pandas/pull/37367#pullrequestreview-570360772",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "8058fd42-96cf-4af8-859e-e34bf79ade60",
        "parentId" : null,
        "authorId" : "cc7022b2-2831-4c63-a4da-d18b0d342508",
        "body" : "This last entry might not really fit in the bug fixes section .. but maybe also not worth adding a dedicated subsection for it in the \"notable (API breaking) bug fixes\"",
        "createdAt" : "2021-01-18T10:33:05Z",
        "updatedAt" : "2021-02-12T14:01:41Z",
        "lastEditedBy" : "cc7022b2-2831-4c63-a4da-d18b0d342508",
        "tags" : [
        ]
      }
    ],
    "commit" : "fbb713d98ae9a1ac8a8deda76075402fc70dd9c8",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +450,454 @@- Bug in :class:`Index` constructor sometimes silently ignorning a specified ``dtype`` (:issue:`38879`)\n- Bug in :func:`pandas.api.types.infer_dtype` not recognizing Series, Index or array with a period dtype (:issue:`23553`)\n- Bug in :func:`pandas.api.types.infer_dtype` raising an error for general :class:`.ExtensionArray` objects. It will now return ``\"unknown-array\"`` instead of raising (:issue:`37367`)\n- Bug in constructing a :class:`Series` from a list and a :class:`PandasDtype` (:issue:`39357`)\n- Bug in :class:`Styler` which caused CSS to duplicate on multiple renders. (:issue:`39395`)"
  }
]