[
  {
    "id" : "433a39c0-b6b2-41cd-a544-db52cf1455a3",
    "prId" : 11928,
    "prUrl" : "https://github.com/lampepfl/dotty/pull/11928#pullrequestreview-624642613",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "98af4886-6f78-4fa6-bd34-0bad8bb66081",
        "parentId" : null,
        "authorId" : "93042d2a-fea3-48fb-8f26-bcce79e4118b",
        "body" : "Why is this an error before? To what I understand `final val` is a \"constant\" (not assignable) value, so it gets initialized in a different order?",
        "createdAt" : "2021-03-30T19:32:57Z",
        "updatedAt" : "2021-03-30T19:34:28Z",
        "lastEditedBy" : "93042d2a-fea3-48fb-8f26-bcce79e4118b",
        "tags" : [
        ]
      },
      {
        "id" : "33ab1c03-83c3-4f16-9a41-fcff72804a93",
        "parentId" : "98af4886-6f78-4fa6-bd34-0bad8bb66081",
        "authorId" : "bc4c7970-6d84-475b-b408-2ed0f22a7bf3",
        "body" : "Only final vals of constant types (such as `false`, `2`, etc.) have different behavior due to const-folding.\r\n\r\nWe don't have a warning now, because at line 5, we already check the effect `this.list!`, thus the access `this.list!` is skipped here. If we comment out line 5, we will have a warning at this line.",
        "createdAt" : "2021-03-30T19:46:00Z",
        "updatedAt" : "2021-03-30T19:46:16Z",
        "lastEditedBy" : "bc4c7970-6d84-475b-b408-2ed0f22a7bf3",
        "tags" : [
        ]
      }
    ],
    "commit" : "7bed8912057b1bd32e7c6a1eb6a84a04a1398140",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +5,9 @@  fun2(5)\n\n  List(5, 9).map(n => 2 + n + list.size)\n\n  final val list = List(1, 2, 3)                 // error"
  }
]