[
  {
    "id" : "7dd7db6e-e2ba-4293-b65b-66c6f26a6a11",
    "prId" : 38678,
    "prUrl" : "https://github.com/ansible/ansible/pull/38678#pullrequestreview-113798284",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "92896fe0-bfe0-4807-ba1f-ab47062ae222",
        "parentId" : null,
        "authorId" : "183d9a20-6a5e-4432-9fe9-9fd6fe9514fb",
        "body" : "Can we use fail_json_aws here too?",
        "createdAt" : "2018-04-19T22:25:48Z",
        "updatedAt" : "2018-05-18T17:41:10Z",
        "lastEditedBy" : "183d9a20-6a5e-4432-9fe9-9fd6fe9514fb",
        "tags" : [
        ]
      }
    ],
    "commit" : "ed659b55388599b3bed12506d19c4626b516d0b8",
    "line" : 41,
    "diffHunk" : "@@ -1,1 +39,43 @@        except Exception as e:\n            module.fail_json(\n                msg=\"Failed to get AWS account information, Try allowing sts:GetCallerIdentity or iam:GetUser permissions.\",\n                exception=traceback.format_exc()\n            )"
  }
]