[
  {
    "id" : "02a7bb90-eda8-44e0-b434-8d3e11d389cf",
    "prId" : 52489,
    "prUrl" : "https://github.com/ansible/ansible/pull/52489#pullrequestreview-204883940",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "21484498-c097-4add-aa43-f13514634499",
        "parentId" : null,
        "authorId" : "0d301bd1-6b47-409f-ac92-439b799b2375",
        "body" : "What is the effect of removing the exception?",
        "createdAt" : "2019-02-18T16:31:03Z",
        "updatedAt" : "2019-02-25T11:35:29Z",
        "lastEditedBy" : "0d301bd1-6b47-409f-ac92-439b799b2375",
        "tags" : [
        ]
      },
      {
        "id" : "736c4d13-a5d7-4d93-80ef-f86deacc3639",
        "parentId" : "21484498-c097-4add-aa43-f13514634499",
        "authorId" : "7268595c-1eb4-4b5f-9277-90f183130a4b",
        "body" : "The exception is added by Ansible by default, so we don't need them individually in each module. So no effect.",
        "createdAt" : "2019-02-18T16:58:30Z",
        "updatedAt" : "2019-02-25T11:35:29Z",
        "lastEditedBy" : "7268595c-1eb4-4b5f-9277-90f183130a4b",
        "tags" : [
        ]
      }
    ],
    "commit" : "db07febb89be9de7084f19406dadcd8f843230a8",
    "line" : 114,
    "diffHunk" : "@@ -1,1 +279,283 @@                ldap.connection.modify_s(ldap.dn, modlist)\n            except Exception as e:\n                module.fail_json(msg=\"Attribute action failed.\", details=to_native(e))\n\n    module.exit_json(changed=changed, modlist=modlist)"
  }
]