[
  {
    "id" : "e8f15260-f0d4-4177-9d5c-9c457c89b281",
    "prId" : 6028,
    "prUrl" : "https://github.com/tensorflow/tensorflow/pull/6028#pullrequestreview-18000332",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "ab1c226b-3d0a-4a8f-b3ab-cc7fabd385c3",
        "parentId" : null,
        "authorId" : "c8f2b008-60f4-4709-b654-47bc9a7795a2",
        "body" : "It's probably a logging.error, although I'm not sure why you would want to catch that error and recover from it.",
        "createdAt" : "2017-01-23T18:31:20Z",
        "updatedAt" : "2017-01-23T23:48:19Z",
        "lastEditedBy" : "c8f2b008-60f4-4709-b654-47bc9a7795a2",
        "tags" : [
        ]
      },
      {
        "id" : "ce8ede43-5376-4a51-b541-0e64c3ed8385",
        "parentId" : "ab1c226b-3d0a-4a8f-b3ab-cc7fabd385c3",
        "authorId" : "7283d004-6b34-4d83-8ecf-e5ef9ec9fc29",
        "body" : "OutOfRangeError is thrown when epoch limit per tf.train.limit_epochs is reached.  In my opinion it should be condition to normally finish training.",
        "createdAt" : "2017-01-23T18:52:54Z",
        "updatedAt" : "2017-01-23T23:48:19Z",
        "lastEditedBy" : "7283d004-6b34-4d83-8ecf-e5ef9ec9fc29",
        "tags" : [
        ]
      },
      {
        "id" : "98ded858-0b9b-44bf-8025-f998165649a1",
        "parentId" : "ab1c226b-3d0a-4a8f-b3ab-cc7fabd385c3",
        "authorId" : "c8f2b008-60f4-4709-b654-47bc9a7795a2",
        "body" : "Ack. Sigh. Thanks for the clarification. Perhaps a comment might help.",
        "createdAt" : "2017-01-23T19:00:39Z",
        "updatedAt" : "2017-01-23T23:48:19Z",
        "lastEditedBy" : "c8f2b008-60f4-4709-b654-47bc9a7795a2",
        "tags" : [
        ]
      },
      {
        "id" : "eabbf37b-3cb6-4bda-8931-af8ca7cf4a44",
        "parentId" : "ab1c226b-3d0a-4a8f-b3ab-cc7fabd385c3",
        "authorId" : "7283d004-6b34-4d83-8ecf-e5ef9ec9fc29",
        "body" : "Good point, added comment.",
        "createdAt" : "2017-01-23T19:11:05Z",
        "updatedAt" : "2017-01-23T23:48:19Z",
        "lastEditedBy" : "7283d004-6b34-4d83-8ecf-e5ef9ec9fc29",
        "tags" : [
        ]
      }
    ],
    "commit" : "8d54cb39b838891dbe76624bbb326621f9e3cee8",
    "line" : null,
    "diffHunk" : "@@ -1,1 +799,803 @@            # OutOfRangeError is thrown when epoch limit per \n            # tf.train.limit_epochs is reached.\n            logging.info('Caught OutOfRangeError. Stopping Training.')\n          if logdir and sv.is_chief:\n            logging.info('Finished training! Saving model to disk.')"
  }
]