[
  {
    "id" : "23d9cdd8-0ee5-48f6-9b91-5d17be0ba51b",
    "prId" : 55188,
    "prUrl" : "https://github.com/kubernetes/kubernetes/pull/55188#pullrequestreview-76310984",
    "prSource" : "GitHub",
    "comments" : [
      {
        "id" : "a0c4d07f-e239-4de1-a915-136cc82c6ccd",
        "parentId" : null,
        "authorId" : "ed12fa4b-7790-4e88-b7d8-5d6a06b0b9f3",
        "body" : "Just curious why do we need this change?",
        "createdAt" : "2017-11-14T01:53:34Z",
        "updatedAt" : "2017-11-14T01:56:30Z",
        "lastEditedBy" : "ed12fa4b-7790-4e88-b7d8-5d6a06b0b9f3",
        "tags" : [
        ]
      },
      {
        "id" : "2e863424-1b2c-4984-9ae2-ed5daa8c5579",
        "parentId" : "a0c4d07f-e239-4de1-a915-136cc82c6ccd",
        "authorId" : "87a378b9-1941-4a57-a346-cf12dbb73416",
        "body" : "I explain this here: https://github.com/kubernetes/kubernetes/pull/55188/commits/238b4a0d8e059e6b648fbb94d324b183fe1dc614\r\n\r\n```\r\nFix TestSummaryProvider.\r\n\r\nassert.Contains() checks if its second argument (which is supposed to be\r\na single element) is contained in its first argument (which is supposed\r\nto be a slice/map etc.) The third and following arguments are supposed\r\nto be message and args for the output in case of failure.\r\n\r\nBecause of this bad form, a failure was hidden, the system container is\r\nnamed \"misc\", not \"system\".\r\n```",
        "createdAt" : "2017-11-14T02:01:00Z",
        "updatedAt" : "2017-11-14T02:01:00Z",
        "lastEditedBy" : "87a378b9-1941-4a57-a346-cf12dbb73416",
        "tags" : [
        ]
      }
    ],
    "commit" : "9c38abd482d7f47c0521ab951a1dc16a9ef0fac2",
    "line" : 5,
    "diffHunk" : "@@ -1,1 +47,51 @@\t\tnodeConfig   = cm.NodeConfig{\n\t\t\tRuntimeCgroupsName: \"/runtime\",\n\t\t\tSystemCgroupsName:  \"/misc\",\n\t\t\tKubeletCgroupsName: \"/kubelet\",\n\t\t}"
  }
]